CREATE TABLE IF NOT EXISTS admins (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('owner', 'editor', 'viewer') NOT NULL DEFAULT 'editor',
    active TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_admins_public_id (public_id),
    UNIQUE KEY uq_admins_email (email),
    KEY idx_admins_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    admin_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_admin_sessions_token_hash (token_hash),
    KEY idx_admin_sessions_admin (admin_id),
    KEY idx_admin_sessions_expires (expires_at),
    CONSTRAINT fk_admin_sessions_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uid VARCHAR(180) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    product_type ENUM('new', 'used') NOT NULL,
    model VARCHAR(160) NOT NULL,
    category VARCHAR(160) NOT NULL DEFAULT '',
    publication_status ENUM('draft', 'review', 'published') NOT NULL DEFAULT 'draft',
    visible TINYINT(1) NOT NULL DEFAULT 1,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    data_json JSON NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at DATETIME(3) NULL,
    deleted_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_products_uid (uid),
    UNIQUE KEY uq_products_slug (slug),
    KEY idx_products_public (publication_status, visible, deleted_at),
    KEY idx_products_type (product_type, deleted_at),
    KEY idx_products_updated (updated_at),
    CONSTRAINT fk_products_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_updated_by FOREIGN KEY (updated_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS articles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uid VARCHAR(180) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    title VARCHAR(240) NOT NULL,
    category VARCHAR(120) NOT NULL DEFAULT '',
    author VARCHAR(120) NOT NULL DEFAULT 'Equipe Brutusmaq',
    publication_status ENUM('draft', 'review', 'published') NOT NULL DEFAULT 'draft',
    visible TINYINT(1) NOT NULL DEFAULT 1,
    popular TINYINT(1) NOT NULL DEFAULT 0,
    data_json JSON NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at DATETIME(3) NULL,
    deleted_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_articles_uid (uid),
    UNIQUE KEY uq_articles_slug (slug),
    KEY idx_articles_public (publication_status, visible, deleted_at, published_at),
    KEY idx_articles_category (category, deleted_at),
    CONSTRAINT fk_articles_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL,
    CONSTRAINT fk_articles_updated_by FOREIGN KEY (updated_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    status ENUM('new', 'in_progress', 'closed', 'spam') NOT NULL DEFAULT 'new',
    reason VARCHAR(120) NOT NULL,
    name VARCHAR(160) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(190) NULL,
    company VARCHAR(190) NULL,
    city_state VARCHAR(160) NULL,
    interest VARCHAR(160) NULL,
    product_slug VARCHAR(140) NULL,
    product_name VARCHAR(180) NULL,
    message TEXT NULL,
    source VARCHAR(180) NOT NULL DEFAULT 'contato.html',
    payload_json JSON NOT NULL,
    privacy_version VARCHAR(32) NOT NULL DEFAULT '2026-07-14',
    assigned_to BIGINT UNSIGNED NULL,
    closed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_leads_public_id (public_id),
    KEY idx_leads_status_created (status, created_at),
    KEY idx_leads_product (product_slug),
    KEY idx_leads_assigned (assigned_to),
    CONSTRAINT fk_leads_assigned_to FOREIGN KEY (assigned_to) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analytics_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_uid VARCHAR(100) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    session_hash CHAR(64) NOT NULL,
    page VARCHAR(180) NOT NULL,
    entity_type VARCHAR(40) NOT NULL DEFAULT 'page',
    entity_id VARCHAR(140) NULL,
    entity_name VARCHAR(180) NULL,
    channel VARCHAR(60) NULL,
    form_type VARCHAR(120) NULL,
    source VARCHAR(180) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_analytics_event_uid (event_uid),
    KEY idx_analytics_occurred (occurred_at),
    KEY idx_analytics_type_occurred (event_type, occurred_at),
    KEY idx_analytics_entity (entity_type, entity_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    public_url VARCHAR(500) NOT NULL,
    mime_type VARCHAR(80) NOT NULL,
    size_bytes INT UNSIGNED NOT NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    alt_text VARCHAR(240) NOT NULL DEFAULT '',
    uploaded_by BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_media_public_id (public_id),
    UNIQUE KEY uq_media_storage_path (storage_path),
    KEY idx_media_created (created_at),
    CONSTRAINT fk_media_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    admin_id BIGINT UNSIGNED NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_uid VARCHAR(180) NULL,
    details_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_audit_admin_created (admin_id, created_at),
    KEY idx_audit_entity (entity_type, entity_uid, created_at),
    CONSTRAINT fk_audit_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
