CREATE TABLE IF NOT EXISTS admin_invitations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    admin_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    invited_by BIGINT UNSIGNED NULL,
    expires_at DATETIME(3) NOT NULL,
    accepted_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_admin_invitations_public_id (public_id),
    UNIQUE KEY uq_admin_invitations_token_hash (token_hash),
    KEY idx_admin_invitations_admin_created (admin_id, created_at),
    KEY idx_admin_invitations_expires (expires_at),
    CONSTRAINT fk_admin_invitations_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_invitations_invited_by FOREIGN KEY (invited_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS editorial_submissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    entity_type ENUM('product', 'article') NOT NULL,
    operation ENUM('create', 'update') NOT NULL,
    entity_uid VARCHAR(180) NULL,
    entity_key VARCHAR(180) NOT NULL,
    product_type ENUM('new', 'used') NULL,
    payload_json JSON NOT NULL,
    base_version INT UNSIGNED NULL,
    status ENUM('draft', 'pending', 'approved', 'rejected', 'cancelled') NOT NULL DEFAULT 'draft',
    submitted_by BIGINT UNSIGNED NOT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    review_note VARCHAR(1000) NULL,
    submitted_at DATETIME(3) NULL,
    reviewed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uq_editorial_submissions_public_id (public_id),
    KEY idx_editorial_submissions_queue (status, submitted_at, updated_at),
    KEY idx_editorial_submissions_author (submitted_by, status, updated_at),
    KEY idx_editorial_submissions_entity (entity_type, entity_uid, updated_at),
    KEY idx_editorial_submissions_key (entity_type, entity_key, updated_at),
    CONSTRAINT fk_editorial_submissions_submitted_by FOREIGN KEY (submitted_by) REFERENCES admins (id) ON DELETE RESTRICT,
    CONSTRAINT fk_editorial_submissions_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
